In [1]:
import pandas as pd
import numpy as np

In [182]:
x_r

   x_r
0    .
1    .
2    .
3    .
4    .
..  ..
93   .
94   .
95   .
96   .
97   .

[98 rows x 1 columns]

In [199]:
    data = pd.read_csv('P11.csv', header=None, names='x')
    data = pd.DataFrame(list(data['x'].str)).T

    x, y = data.shape
    
    x_l = pd.DataFrame(['.'] * x, columns=['x_l'])
    x_r = pd.DataFrame(['.'] * x, columns=['x_r'])
    
    data

    x  x  x  x  x  x  x  x  x  x  ...  x  x  x  x  x  x  x  x  x  x
0   L  L  L  L  L  L  L  L  L  .  ...  L  L  L  L  L  L  L  L  L  L
1   L  L  L  L  L  L  L  L  L  L  ...  L  .  L  L  L  L  L  L  L  L
2   L  L  L  L  L  L  L  L  L  .  ...  L  L  L  L  L  L  L  L  L  L
3   L  L  L  L  L  L  L  L  L  L  ...  L  .  L  L  L  L  L  L  L  L
4   L  L  L  L  L  L  L  L  L  L  ...  L  .  L  L  L  L  L  L  L  L
.. .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
92  L  L  L  L  L  L  L  L  L  L  ...  L  .  L  L  L  L  L  .  L  L
93  L  L  L  L  L  L  L  L  L  .  ...  L  L  L  L  L  L  L  L  L  L
94  L  L  L  L  L  L  L  L  L  L  ...  L  L  L  L  L  L  L  L  L  L
95  L  L  L  L  L  L  L  L  L  L  ...  L  .  L  L  L  L  L  L  L  L
96  L  L  L  L  L  L  L  L  L  .  ...  L  .  L  L  L  L  L  L  L  L

[97 rows x 98 columns]

In [200]:
    data = pd.concat([x_l, data, x_r], axis=1)
    data.loc[-1]  = ['.'] * (y + 2)
    data.loc[x] = ['.'] * (y + 2)
    data.index = data.index + 1  # shifting index
    data.sort_index(inplace=True)

In [194]:
def prepare_data():

    data = pd.read_csv('P11.csv', header=None, names='x')
    data = pd.DataFrame(list(data['x'].str)).T

    x, y = data.shape
    
    x_l = pd.DataFrame(['.'] * y, columns=['x_l'])
    x_r = pd.DataFrame(['.'] * y, columns=['x_r'])

    data = pd.concat([x_l, data, x_r], axis=1)
    data.loc[-1]  = ['.'] * (x + 2)
    data.loc[x] = ['.'] * (x + 2)
    data.index = data.index + 1  # shifting index
    data.sort_index(inplace=True) 
    
    return data

In [201]:
start_x, start_y = (1, 1)
end_x, end_y = (data.shape[0] - 2, data.shape[1] - 2)

### part 1

In [196]:
def take_seat(data, x, y):
    
    if data.iloc[x, y] == '.':
        return '.'
    
    else:
    
        seats_around = []

        seats_around.append(data.iloc[x-1, y-1])
        seats_around.append(data.iloc[x-1, y])
        seats_around.append(data.iloc[x-1, y+1])
        seats_around.append(data.iloc[x, y-1])
        seats_around.append(data.iloc[x, y+1])
        seats_around.append(data.iloc[x+1, y-1])
        seats_around.append(data.iloc[x+1, y])
        seats_around.append(data.iloc[x+1, y+1])

        taken_around = sum(map(lambda x : x == '#', seats_around))
        
        #print(data.iloc[x, y], taken_around)
        
        if data.iloc[x, y] == 'L' and taken_around == 0:
            return '#'
        
        if data.iloc[x, y] == 'L' and taken_around > 0:
            return 'L'
        
        if data.iloc[x, y] == '#' and taken_around < 4:
            return '#'
        if data.iloc[x, y] == '#' and taken_around >= 4:
            return 'L'

In [173]:
data = prepare_data()

ValueError: cannot set a row with mismatched columns

In [202]:
CHANGES = 99

while CHANGES>0:
    
#for i in range(2):

    data_new = data.copy()

    changes = 0

    for i in range(start_x, end_x+1):
        for j in range(start_y, end_y+1):
            pos_old = data.iloc[i, j]
            pos_new = take_seat(data, i, j)

            if pos_old != pos_new:
                changes += 1

            data_new.iloc[i, j] = take_seat(data, i, j)

    data = data_new.copy()
    
    CHANGES = changes
    
    print(CHANGES)

7947
7824
7463
7334
6976
6857
6565
6446
6183
6069
5814
5707
5461
5357
5105
5001
4767
4676
4457
4362
4164
4085
3907
3830
3671
3603
3444
3361
3217
3158
3034
2964
2833
2777
2657
2603
2489
2451
2371
2337
2259
2226
2146
2111
2025
1978
1894
1857
1774
1732
1646
1612
1532
1491
1412
1376
1294
1254
1174
1141
1062
1017
930
886
799
760
680
645
569
536
467
436
372
352
312
294
253
234
195
181
143
127
95
83
59
52
40
35
24
20
10
5
0

In [204]:
data_new.applymap(lambda x: 1 if x == '#' else 0).sum().sum()

2448